<?php
declare(strict_types=1);

require_once __DIR__ . '/../config/session.php';
start_secure_session();

if (!isset($_SESSION['user_id']) || (string) ($_SESSION['role'] ?? '') !== 'admin') {
    header('Location: ../index.php');
    exit;
}

require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../config/csrf.php';
require_once __DIR__ . '/image_compress.php';

$flashError = '';
$flashSuccess = '';

if (isset($_SESSION['flash_error'])) {
    $flashError = (string) $_SESSION['flash_error'];
    unset($_SESSION['flash_error']);
}
if (isset($_SESSION['flash_success'])) {
    $flashSuccess = (string) $_SESSION['flash_success'];
    unset($_SESSION['flash_success']);
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !csrf_verify($_POST['csrf_token'] ?? null)) {
    $_SESSION['flash_error'] = 'คำขอไม่ถูกต้องหรือโทเค็นหมดอายุ กรุณาลองใหม่อีกครั้ง';
    header('Location: settings.php');
    exit;
}

try {
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS system_settings (
            key_name VARCHAR(100) PRIMARY KEY,
            value_text VARCHAR(255) NOT NULL
        )"
    );

    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS advisors (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            prefix VARCHAR(30) NOT NULL,
            full_name VARCHAR(190) NOT NULL,
            avatar_filename VARCHAR(255),
            is_active SMALLINT NOT NULL DEFAULT 1,
            created_at TIMESTAMP NOT NULL DEFAULT now()
        )"
    );
    $pdo->exec("CREATE INDEX IF NOT EXISTS idx_advisors_active ON advisors (is_active)");
} catch (Throwable $e) {
    error_log('[ADMIN_SETTINGS] ensure tables failed: ' . $e->getMessage());
    $flashError = 'ไม่สามารถเตรียมโครงสร้างข้อมูลระบบตั้งค่าได้';
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = (string) ($_POST['action'] ?? '');

    if (isset($_POST['update_advisor_avatar']) && (string) $_POST['update_advisor_avatar'] === '1') {
        $advisorId = (int) ($_POST['advisor_id'] ?? 0);
        if ($advisorId <= 0) {
            $_SESSION['flash_error'] = 'คำขอเปลี่ยนรูปอาจารย์ไม่ถูกต้อง';
            header('Location: settings.php');
            exit;
        }

        try {
            $sel = $pdo->prepare('SELECT avatar_filename FROM advisors WHERE id = :id LIMIT 1');
            $sel->execute([':id' => $advisorId]);
            $advRow = $sel->fetch(PDO::FETCH_ASSOC);
            if (!$advRow) {
                $_SESSION['flash_error'] = 'ไม่พบข้อมูลอาจารย์ที่ปรึกษา';
                header('Location: settings.php');
                exit;
            }

            $oldFilename = trim((string) ($advRow['avatar_filename'] ?? ''));

            if (!isset($_FILES['advisor_avatar']) || !is_array($_FILES['advisor_avatar'])) {
                $_SESSION['flash_error'] = 'กรุณาเลือกไฟล์รูปภาพ';
                header('Location: settings.php');
                exit;
            }

            $fileErr = (int) ($_FILES['advisor_avatar']['error'] ?? UPLOAD_ERR_NO_FILE);
            if ($fileErr !== UPLOAD_ERR_OK) {
                $_SESSION['flash_error'] = 'อัปโหลดไฟล์ไม่สำเร็จ กรุณาลองใหม่';
                header('Location: settings.php');
                exit;
            }

            $uploadDir = __DIR__ . '/../uploads/advisors/';
            if (!is_dir($uploadDir)) {
                mkdir($uploadDir, 0755, true);
            }

            $newFilename = saveLocalUploadedImageAsWebp($_FILES['advisor_avatar'], $uploadDir, 'adv_', 500);
            if ($newFilename === null) {
                $_SESSION['flash_error'] = 'ไม่สามารถบันทึกไฟล์รูปภาพได้';
                header('Location: settings.php');
                exit;
            }

            $upd = $pdo->prepare('UPDATE advisors SET avatar_filename = :fn WHERE id = :id');
            $upd->execute([':fn' => $newFilename, ':id' => $advisorId]);

            if ($oldFilename !== '') {
                $oldPath = $uploadDir . basename($oldFilename);
                if (is_file($oldPath)) {
                    @unlink($oldPath);
                }
            }

            $_SESSION['flash_success'] = 'อัปเดตรูปอาจารย์ที่ปรึกษาเรียบร้อยแล้ว';
        } catch (Throwable $e) {
            error_log('[ADMIN_SETTINGS] update advisor avatar failed: ' . $e->getMessage());
            $_SESSION['flash_error'] = 'ไม่สามารถอัปเดตรูปอาจารย์ได้';
        }

        header('Location: settings.php');
        exit;
    }

    if ($action === 'toggle_registration') {
        $isOpen = isset($_POST['registration_open']) ? '1' : '0';
        try {
            $stmt = $pdo->prepare(
                "INSERT INTO system_settings (key_name, value_text)
                 VALUES ('student_registration_open', :value_text)
                 ON CONFLICT (key_name) DO UPDATE SET value_text = EXCLUDED.value_text"
            );
            $stmt->execute([':value_text' => $isOpen]);
            $_SESSION['flash_success'] = $isOpen === '1'
                ? 'เปิดรับสมัครนักศึกษาเรียบร้อยแล้ว'
                : 'ปิดรับสมัครนักศึกษาเรียบร้อยแล้ว';
        } catch (Throwable $e) {
            error_log('[ADMIN_SETTINGS] toggle registration failed: ' . $e->getMessage());
            $_SESSION['flash_error'] = 'ไม่สามารถอัปเดตสถานะการรับสมัครได้';
        }

        header('Location: settings.php');
        exit;
    }

    if ($action === 'add_year') {
        $year = trim((string) ($_POST['academic_year'] ?? ''));
        if ($year === '') {
            $_SESSION['flash_error'] = 'กรุณาระบุปีการศึกษา';
            header('Location: settings.php');
            exit;
        }

        try {
            $insert = $pdo->prepare('INSERT INTO academic_years (year) VALUES (:year)');
            $insert->execute([':year' => $year]);
            $_SESSION['flash_success'] = 'เพิ่มปีการศึกษาเรียบร้อยแล้ว';
        } catch (Throwable $e) {
            error_log('[ADMIN_SETTINGS] add year failed: ' . $e->getMessage());
            $_SESSION['flash_error'] = 'ไม่สามารถเพิ่มปีการศึกษาได้ (อาจมีข้อมูลซ้ำ)';
        }

        header('Location: settings.php');
        exit;
    }

    if ($action === 'delete_year') {
        $yearId = (int) ($_POST['year_id'] ?? 0);
        if ($yearId <= 0) {
            $_SESSION['flash_error'] = 'คำขอลบปีการศึกษาไม่ถูกต้อง';
            header('Location: settings.php');
            exit;
        }

        try {
            $delete = $pdo->prepare('DELETE FROM academic_years WHERE id = :id');
            $delete->execute([':id' => $yearId]);
            $_SESSION['flash_success'] = 'ลบปีการศึกษาเรียบร้อยแล้ว';
        } catch (Throwable $e) {
            error_log('[ADMIN_SETTINGS] delete year failed: ' . $e->getMessage());
            $_SESSION['flash_error'] = 'ไม่สามารถลบปีการศึกษาได้ เนื่องจากมีโครงงานอ้างอิงอยู่';
        }

        header('Location: settings.php');
        exit;
    }

    if ($action === 'add_category') {
        $categoryName = trim((string) ($_POST['category_name'] ?? ''));
        if ($categoryName === '') {
            $_SESSION['flash_error'] = 'กรุณาระบุชื่อหมวดหมู่';
            header('Location: settings.php');
            exit;
        }

        try {
            $insert = $pdo->prepare('INSERT INTO categories (name) VALUES (:name)');
            $insert->execute([':name' => $categoryName]);
            $_SESSION['flash_success'] = 'เพิ่มหมวดหมู่เรียบร้อยแล้ว';
        } catch (Throwable $e) {
            error_log('[ADMIN_SETTINGS] add category failed: ' . $e->getMessage());
            $_SESSION['flash_error'] = 'ไม่สามารถเพิ่มหมวดหมู่ได้ (อาจมีข้อมูลซ้ำ)';
        }

        header('Location: settings.php');
        exit;
    }

    if ($action === 'delete_category') {
        $categoryId = (int) ($_POST['category_id'] ?? 0);
        if ($categoryId <= 0) {
            $_SESSION['flash_error'] = 'คำขอลบหมวดหมู่ไม่ถูกต้อง';
            header('Location: settings.php');
            exit;
        }

        try {
            $delete = $pdo->prepare('DELETE FROM categories WHERE id = :id');
            $delete->execute([':id' => $categoryId]);
            $_SESSION['flash_success'] = 'ลบหมวดหมู่เรียบร้อยแล้ว';
        } catch (Throwable $e) {
            error_log('[ADMIN_SETTINGS] delete category failed: ' . $e->getMessage());
            $_SESSION['flash_error'] = 'ไม่สามารถลบหมวดหมู่ได้ เนื่องจากมีโครงงานอ้างอิงอยู่';
        }

        header('Location: settings.php');
        exit;
    }

    if ($action === 'add_advisor') {
        $prefix = trim((string) ($_POST['advisor_prefix'] ?? ''));
        $fullName = trim((string) ($_POST['advisor_full_name'] ?? ''));
        $avatarFilename = null;

        if ($prefix === '' || $fullName === '') {
            $_SESSION['flash_error'] = 'กรุณากรอกคำนำหน้าและชื่ออาจารย์ให้ครบถ้วน';
            header('Location: settings.php');
            exit;
        }

        // ระบบอัปโหลดรูปภาพ
        if (isset($_FILES['advisor_avatar']) && $_FILES['advisor_avatar']['error'] === UPLOAD_ERR_OK) {
            $uploadDir = __DIR__ . '/../uploads/advisors/';
            $avatarFilename = saveLocalUploadedImageAsWebp($_FILES['advisor_avatar'], $uploadDir, 'adv_', 500);
            if ($avatarFilename === null) {
                $_SESSION['flash_error'] = 'ไม่สามารถบันทึกไฟล์รูปภาพได้';
                header('Location: settings.php');
                exit;
            }
        }

        try {
            $insert = $pdo->prepare(
                'INSERT INTO advisors (prefix, full_name, avatar_filename, is_active)
                 VALUES (:prefix, :full_name, :avatar_filename, 1)'
            );
            $insert->execute([
                ':prefix' => $prefix,
                ':full_name' => $fullName,
                ':avatar_filename' => $avatarFilename,
            ]);
            $_SESSION['flash_success'] = 'เพิ่มอาจารย์ที่ปรึกษาเรียบร้อยแล้ว';
        } catch (Throwable $e) {
            error_log('[ADMIN_SETTINGS] add advisor failed: ' . $e->getMessage());
            $_SESSION['flash_error'] = 'ไม่สามารถเพิ่มอาจารย์ที่ปรึกษาได้';
        }

        header('Location: settings.php');
        exit;
    }

    if ($action === 'delete_advisor') {
        $advisorId = (int) ($_POST['advisor_id'] ?? 0);
        if ($advisorId <= 0) {
            $_SESSION['flash_error'] = 'คำขอลบอาจารย์ไม่ถูกต้อง';
            header('Location: settings.php');
            exit;
        }

        try {
            $delete = $pdo->prepare('DELETE FROM advisors WHERE id = :id');
            $delete->execute([':id' => $advisorId]);
            $_SESSION['flash_success'] = 'ลบอาจารย์ที่ปรึกษาเรียบร้อยแล้ว';
        } catch (Throwable $e) {
            error_log('[ADMIN_SETTINGS] delete advisor failed: ' . $e->getMessage());
            $_SESSION['flash_error'] = 'ไม่สามารถลบอาจารย์ที่ปรึกษาได้';
        }

        header('Location: settings.php');
        exit;
    }

    if ($action === 'toggle_advisor_status') {
        $advisorId = (int) ($_POST['advisor_id'] ?? 0);
        $nextStatus = (int) ($_POST['next_status'] ?? 0) === 1 ? 1 : 0;
        if ($advisorId <= 0) {
            $_SESSION['flash_error'] = 'คำขอปรับสถานะอาจารย์ไม่ถูกต้อง';
            header('Location: settings.php');
            exit;
        }

        try {
            $update = $pdo->prepare('UPDATE advisors SET is_active = :status WHERE id = :id');
            $update->execute([':status' => $nextStatus, ':id' => $advisorId]);
        } catch (Throwable $e) {
            error_log('[ADMIN_SETTINGS] toggle advisor status failed: ' . $e->getMessage());
            $_SESSION['flash_error'] = 'ไม่สามารถอัปเดตสถานะอาจารย์ได้';
        }

        header('Location: settings.php');
        exit;
    }
}

$adminName = trim((string) ($_SESSION['name'] ?? $_SESSION['user_name'] ?? 'Administrator'));
$adminEmail = '';
try {
    $userStmt = $pdo->prepare('SELECT email FROM users WHERE id = :id LIMIT 1');
    $userStmt->execute([':id' => (int) $_SESSION['user_id']]);
    $currentAdmin = $userStmt->fetch();
    if ($currentAdmin) {
        $adminEmail = trim((string) ($currentAdmin['email'] ?? ''));
    }
} catch (Throwable $e) {
    error_log('[ADMIN_SETTINGS] load admin profile failed: ' . $e->getMessage());
}

$avatar = $adminName !== '' ? (function_exists('mb_substr') ? mb_substr($adminName, 0, 1, 'UTF-8') : substr($adminName, 0, 1)) : 'A';
$avatar = strtoupper((string) $avatar);

$registrationOpen = true;
$academicYears = [];
$categories = [];
$advisors = [];

try {
    $settingStmt = $pdo->prepare("SELECT value_text FROM system_settings WHERE key_name = 'student_registration_open' LIMIT 1");
    $settingStmt->execute();
    $settingRow = $settingStmt->fetch();
    if ($settingRow && isset($settingRow['value_text'])) {
        $registrationOpen = (string) $settingRow['value_text'] === '1';
    }

    $yearsStmt = $pdo->query('SELECT id, year FROM academic_years ORDER BY year ASC');
    $academicYears = $yearsStmt->fetchAll(PDO::FETCH_ASSOC);

    $categoryStmt = $pdo->query('SELECT id, name FROM categories ORDER BY name ASC');
    $categories = $categoryStmt->fetchAll(PDO::FETCH_ASSOC);

    $advisorStmt = $pdo->query('SELECT id, prefix, full_name, avatar_filename, is_active FROM advisors ORDER BY id DESC');
    $advisors = $advisorStmt->fetchAll(PDO::FETCH_ASSOC);
} catch (Throwable $e) {
    error_log('[ADMIN_SETTINGS] load data failed: ' . $e->getMessage());
    if ($flashError === '') {
        $flashError = 'ไม่สามารถโหลดข้อมูลตั้งค่าระบบบางส่วนได้';
    }
}

$pageTitle = 'ตั้งค่าระบบ';
$pageTitleDataTh = 'ตั้งค่าระบบ';
$pageTitleDataEn = 'System Settings';
$pageSubtitle = 'จัดการค่าระบบพื้นฐานสำหรับการใช้งานภายในแดชบอร์ด';
$pageSubtitleDataTh = 'จัดการค่าระบบพื้นฐานสำหรับการใช้งานภายในแดชบอร์ด';
$pageSubtitleDataEn = 'Manage core system settings for the dashboard';
$yearsCount = count($academicYears);
$categoriesCount = count($categories);
$advisorsCount = count($advisors);
$currentYear = (string) date('Y');
?>
<!doctype html>
<html lang="th">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>System Settings - RMUTI MT Gallery</title>
  <?php require_once __DIR__ . '/../config/site_theme_head.php'; ?>
  <script src="https://cdn.tailwindcss.com"></script>
  <?php require_once __DIR__ . '/../config/site_tailwind_config.php'; ?>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.13/cropper.min.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.13/cropper.min.js"></script>
  <style>
    :root { --mt-red:#D32F2F; --mt-red-dark:#B71C1C; --bg-secondary:#F4F5F6; --text-muted:#8A8A8A; --border:#E3E3E3; --card:#FCFCFD; }
    body { font-family:'DM Sans',sans-serif; background:var(--bg-secondary); color:#111827; }
    .font-display { font-family:'Cormorant Garamond',serif; }
    .settings-card { border:1px solid var(--border); border-radius:18px; background:var(--card); box-shadow:0 8px 26px rgba(15,23,42,.04); }
    .settings-input { height:42px; width:100%; border:1px solid #DCE1E7; border-radius:12px; background:#fff; padding:0 12px; font-size:13px; color:#374151; outline:none; }
    .settings-input:focus { border-color:#BAC3CF; box-shadow:0 0 0 3px rgba(148,163,184,.16); }
    .soft-item { border:1px solid #DFE3E8; border-radius:12px; background:#F9FAFB; min-height:40px; padding:8px 12px; }
    .modal-overlay {
      position: fixed; inset: 0; display: flex; align-items: center; justify-content: center;
      background: rgba(0, 0, 0, .48); z-index: 1000; padding: 16px;
      opacity: 0; visibility: hidden; pointer-events: none;
      transition: opacity 300ms ease-out, visibility 300ms ease-out;
    }
    .modal-overlay.open { visibility: visible; pointer-events: auto; }
    .modal-overlay.is-visible { opacity: 1; }
    .modal-panel { transition: all 300ms ease-out; transform: scale(.95); opacity: 0; }
    .modal-overlay.is-visible .modal-panel { transform: scale(1); opacity: 1; }
    .vertical-align-middle { vertical-align: middle; }
  </style>
  <?php require_once __DIR__ . '/../config/site_dark_styles.php'; ?>
</head>
<body class="h-screen overflow-hidden dark:bg-[#121212] dark:text-gray-100">
  <div class="flex h-screen min-h-0 overflow-hidden">
    <?php include __DIR__ . '/sidebar.php'; ?>

    <div class="flex-1 flex flex-col h-full min-h-0 overflow-hidden">
      <main class="flex-1 min-h-0 overflow-y-auto px-6 py-6 md:px-8 md:py-8">
        <div class="mx-auto max-w-7xl">
          <?php include __DIR__ . '/topbar.php'; ?>
        <section class="settings-card mt-6 border-t-2 <?= $registrationOpen ? 'border-t-[#18B981]' : 'border-t-[#D32F2F]' ?> p-6 dark:bg-[#1e1e1e] dark:border-[#333333]">
          <form method="post" action="./settings.php" id="registration-form">
            <input type="hidden" name="action" value="toggle_registration" />
            <?= csrf_input() ?>
            <div class="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
              <div class="flex min-w-0 items-start gap-4">
                <div class="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#FFF0F2] text-[var(--mt-red)] dark:bg-rose-950/40 dark:text-rose-400">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path d="M10 10a4 4 0 100-8 4 4 0 000 8z"/><path fill-rule="evenodd" d="M.458 16.042C1.732 13.133 4.522 11 10 11s8.268 2.133 9.542 5.042A1 1 0 0118.63 17H1.37a1 1 0 01-.912-1.458z" clip-rule="evenodd"/></svg>
                </div>
                <div class="min-w-0">
                  <h2 class="text-[30px] leading-none font-display text-[#141821] dark:text-white">Student Registration</h2>
                  <p class="mt-1 text-sm text-[var(--text-muted)]">ควบคุมว่านักศึกษาสามารถลงทะเบียนบัญชีได้หรือไม่</p>
                </div>
              </div>

              <label class="inline-flex cursor-pointer items-center gap-3">
                <input id="registration-open" type="checkbox" name="registration_open" value="1" class="sr-only" <?= $registrationOpen ? 'checked' : '' ?> />
                <span id="registration-track" class="relative h-8 w-14 rounded-full border border-[#D0D5DD] bg-white transition dark:bg-[#1e1e1e] dark:border-[#333333] <?= $registrationOpen ? 'dark:!bg-emerald-950 dark:!border-emerald-700' : '' ?>">
                  <span id="registration-thumb" class="absolute left-1 top-1 h-6 w-6 rounded-full bg-[#9CA3AF] shadow transition-all duration-200"></span>
                </span>
                <span class="rounded-full px-3 py-1 text-xs font-semibold <?= $registrationOpen ? 'bg-[#ECFDF5] text-[#0F766E] dark:bg-emerald-950/60 dark:text-emerald-400 dark:border dark:border-emerald-900/60' : 'bg-[#F3F4F6] text-[#6B7280] dark:bg-[#262626] dark:text-gray-300' ?>">
                  <?= $registrationOpen ? 'Open' : 'Closed' ?>
                </span>
              </label>
            </div>
          </form>

          <div class="mt-5 rounded-2xl border px-4 py-3 text-sm font-medium <?= $registrationOpen ? 'border-[#C8F0E5] bg-[#EAFBF6] text-[#147E6E] dark:bg-emerald-950/30 dark:border-emerald-900/60 dark:text-emerald-300' : 'border-[#E5E7EB] bg-[#F7F8FA] text-[#6B7280] dark:border-[#333333] dark:bg-[#262626] dark:text-gray-300' ?>">
            <span class="mr-2 inline-block h-2.5 w-2.5 rounded-full <?= $registrationOpen ? 'bg-[#34D399]' : 'bg-[#D1D5DB]' ?>"></span>
            <?= $registrationOpen
                ? 'ขณะนี้เปิดรับสมัครแล้ว นักเรียนใหม่สามารถสร้างบัญชีได้'
                : 'การลงทะเบียนปิดแล้ว นักเรียนใหม่ไม่สามารถลงทะเบียนได้ในขณะนี้' ?>
          </div>
        </section>

        <div class="mt-6 grid grid-cols-1 gap-5 xl:grid-cols-2">
          <section class="settings-card border-t-2 border-t-[#8DC8F0] p-5 dark:bg-[#1e1e1e] dark:border-[#333333]">
            <div class="flex items-start gap-3">
              <div class="grid h-10 w-10 place-items-center rounded-xl bg-[#EDF6FE] text-[#4B87B0] dark:bg-sky-950/40 dark:text-sky-400">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v8a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zM4 8h12v6H4V8z" clip-rule="evenodd"/></svg>
              </div>
              <div>
                <h3 class="text-[31px] leading-none font-display text-[#141821] dark:text-white">Academic Years</h3>
                <p class="mt-1 text-sm text-[var(--text-muted)]"><?= (int) $yearsCount ?> years registered</p>
              </div>
            </div>

            <div class="mt-4 space-y-2">
              <?php if (empty($academicYears)): ?>
                <div class="soft-item text-sm text-[#9CA3AF]">No academic years yet.</div>
              <?php else: ?>
                <?php foreach ($academicYears as $yearRow): ?>
                  <?php $yearValue = (string) ($yearRow['year'] ?? ''); ?>
                  <div class="soft-item group flex items-center justify-between gap-3 text-sm font-semibold text-[#23272F] dark:bg-[#262626] dark:border-[#333333] dark:text-gray-100">
                    <div class="flex min-w-0 items-center gap-2">
                      <span class="truncate"><?= htmlspecialchars($yearValue, ENT_QUOTES, 'UTF-8') ?></span>
                      <?php if ($yearValue === $currentYear): ?>
                        <span class="rounded-full bg-[#DCEFFD] px-2 py-0.5 text-[10px] font-semibold text-[#2E6E9D] dark:bg-sky-950/60 dark:text-sky-300 dark:border dark:border-sky-900/60">Active</span>
                      <?php endif; ?>
                    </div>
                    <button type="button" class="open-delete-item-btn inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-md border border-[#F2C7C7] bg-[#FFF8F8] text-[#C62828] opacity-0 transition group-hover:opacity-100 dark:bg-rose-950/30 dark:border-rose-900/60 dark:text-rose-400 dark:hover:bg-rose-900/50" data-delete-action="delete_year" data-delete-id="<?= (int) ($yearRow['id'] ?? 0) ?>" data-delete-id-field="year_id" data-delete-name="<?= htmlspecialchars($yearValue, ENT_QUOTES, 'UTF-8') ?>" data-delete-title="ลบปีการศึกษา" data-delete-message="ยืนยันการลบปีการศึกษานี้ หากมีโครงงานใช้งานอยู่จะไม่สามารถลบได้">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path stroke-linecap="round" stroke-linejoin="round" d="M3 6.75h18M9.75 6.75V5.25A2.25 2.25 0 0112 3h0a2.25 2.25 0 012.25 2.25v1.5m-7.5 0L7.5 19.5A2.25 2.25 0 009.75 21h4.5a2.25 2.25 0 002.25-1.5l.75-12.75M10 11.25v5.5m4-5.5v5.5"/></svg>
                    </button>
                  </div>
                <?php endforeach; ?>
              <?php endif; ?>
            </div>

            <form method="post" action="./settings.php" class="mt-4 flex items-center gap-2 border-t border-[#E5E7EB] pt-4 dark:border-[#333333]">
              <input type="hidden" name="action" value="add_year" />
              <?= csrf_input() ?>
              <input type="text" name="academic_year" placeholder="e.g. 2027" class="settings-input dark:bg-[#1e1e1e] dark:border-gray-700 dark:text-white dark:placeholder-gray-500 dark:focus:border-[var(--mt-red)] dark:focus:ring-[var(--mt-red)]/20" />
              <button type="submit" class="inline-flex h-[42px] shrink-0 items-center gap-1 rounded-xl bg-[#4B87B0] px-4 text-xs font-semibold text-white hover:bg-[#3D7398]">
                <span>+</span>
                Add Year
              </button>
            </form>
          </section>

          <section class="settings-card border-t-2 border-t-[#E56E73] p-5 dark:bg-[#1e1e1e] dark:border-[#333333]">
            <div class="flex items-start gap-3">
              <div class="grid h-10 w-10 place-items-center rounded-xl bg-[#FFF1F3] text-[#D24956] dark:bg-rose-950/40 dark:text-rose-400">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M2.93 9.34a1 1 0 010-1.41l4.99-4.99A2 2 0 019.33 2h3.75a2 2 0 012 2v3.75a2 2 0 01-.59 1.41l-4.99 4.99a1 1 0 01-1.41 0L2.93 9.34zM11 6a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"/></svg>
              </div>
              <div>
                <h3 class="text-[31px] leading-none font-display text-[#141821] dark:text-white">Categories</h3>
                <p class="mt-1 text-sm text-[var(--text-muted)]"><?= (int) $categoriesCount ?> categories available</p>
              </div>
            </div>

            <div class="mt-4 space-y-2">
              <?php if (empty($categories)): ?>
                <div class="soft-item text-sm text-[#9CA3AF]">No categories yet.</div>
              <?php else: ?>
                <?php foreach ($categories as $category): ?>
                  <?php $categoryName = (string) ($category['name'] ?? ''); ?>
                  <div class="soft-item group flex items-center justify-between gap-3 text-sm text-[#23272F] dark:bg-[#262626] dark:border-[#333333] dark:text-gray-100">
                    <div class="flex min-w-0 items-center gap-2">
                      <span class="h-1.5 w-1.5 rounded-full bg-[#D24956]"></span>
                      <span class="truncate"><?= htmlspecialchars($categoryName, ENT_QUOTES, 'UTF-8') ?></span>
                    </div>
                    <button type="button" class="open-delete-item-btn inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-md border border-[#F2C7C7] bg-[#FFF8F8] text-[#C62828] opacity-0 transition group-hover:opacity-100 dark:bg-rose-950/30 dark:border-rose-900/60 dark:text-rose-400 dark:hover:bg-rose-900/50" data-delete-action="delete_category" data-delete-id="<?= (int) ($category['id'] ?? 0) ?>" data-delete-id-field="category_id" data-delete-name="<?= htmlspecialchars($categoryName, ENT_QUOTES, 'UTF-8') ?>" data-delete-title="ลบหมวดหมู่" data-delete-message="ยืนยันการลบหมวดหมู่นี้ หากมีโครงงานใช้งานอยู่จะไม่สามารถลบได้">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path stroke-linecap="round" stroke-linejoin="round" d="M3 6.75h18M9.75 6.75V5.25A2.25 2.25 0 0112 3h0a2.25 2.25 0 012.25 2.25v1.5m-7.5 0L7.5 19.5A2.25 2.25 0 009.75 21h4.5a2.25 2.25 0 002.25-1.5l.75-12.75M10 11.25v5.5m4-5.5v5.5"/></svg>
                    </button>
                  </div>
                <?php endforeach; ?>
              <?php endif; ?>
            </div>

            <form method="post" action="./settings.php" class="mt-4 flex items-center gap-2 border-t border-[#E5E7EB] pt-4 dark:border-[#333333]">
              <input type="hidden" name="action" value="add_category" />
              <?= csrf_input() ?>
              <input type="text" name="category_name" placeholder="e.g. Interactive Design" class="settings-input dark:bg-[#1e1e1e] dark:border-gray-700 dark:text-white dark:placeholder-gray-500 dark:focus:border-[var(--mt-red)] dark:focus:ring-[var(--mt-red)]/20" />
              <button type="submit" class="inline-flex h-[42px] shrink-0 items-center gap-1 rounded-xl bg-[var(--mt-red)] px-4 text-xs font-semibold text-white hover:bg-[var(--mt-red-dark)]">
                <span>+</span>
                Add
              </button>
            </form>
          </section>
        </div>

        <section class="settings-card mt-6 border-t-2 border-t-[#93C5FD] p-5 dark:bg-[#1e1e1e] dark:border-[#333333]">
          <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
            <div>
              <h3 class="text-[31px] leading-none font-display text-[#141821] dark:text-white">Manage Advisors</h3>
              <p class="mt-1 text-sm text-[var(--text-muted)]"><?= (int) $advisorsCount ?> advisors in system</p>
            </div>
          </div>

          <div class="mt-4 overflow-hidden rounded-2xl border border-[#E5E7EB] dark:border-[#333333]">
            <table class="w-full" style="table-layout: fixed;">
              <thead>
                <tr class="border-b border-[#E5E7EB] bg-[#FAFBFC] text-[11px] uppercase tracking-[0.1em] text-[#8A8F98] dark:border-[#333333] dark:bg-[#262626] dark:text-gray-400">
                  <th class="w-[80px] px-4 py-3 text-center whitespace-nowrap">Avatar</th>
                  <th class="w-full px-4 py-3 text-left whitespace-nowrap">Name</th>
                  <th class="w-[210px] px-4 py-3 text-center whitespace-nowrap">Actions</th>
                </tr>
              </thead>
              <tbody>
                <?php if (empty($advisors)): ?>
                  <tr>
                    <td colspan="3" class="px-4 py-6 text-sm text-[#9CA3AF]">ยังไม่มีข้อมูลอาจารย์ที่ปรึกษา</td>
                  </tr>
                <?php else: ?>
                  <?php foreach ($advisors as $advisor): ?>
                    <?php
                      $advisorPrefix = trim((string) ($advisor['prefix'] ?? ''));
                      $advisorFullName = trim((string) ($advisor['full_name'] ?? ''));
                      $advisorDisplayName = trim($advisorPrefix . ' ' . $advisorFullName);
                      $advisorAvatarFile = trim((string) ($advisor['avatar_filename'] ?? ''));
                      $advisorAvatarUrl = $advisorAvatarFile !== '' ? '../uploads/advisors/' . rawurlencode($advisorAvatarFile) : '';
                      $advisorAvatarLetter = $advisorDisplayName !== '' ? (function_exists('mb_substr') ? mb_substr($advisorDisplayName, 0, 1, 'UTF-8') : substr($advisorDisplayName, 0, 1)) : 'A';
                      $advisorAvatarLetter = strtoupper((string) $advisorAvatarLetter);
                      $isActive = (int) ($advisor['is_active'] ?? 0) === 1;
                    ?>
                    <tr class="border-b border-[#EFF2F5] last:border-b-0 dark:border-[#333333]">
                      <td class="w-[80px] px-4 py-3 vertical-align-middle text-center">
                        <button
                          type="button"
                          class="group relative mx-auto block h-10 w-10 overflow-hidden rounded-full border border-gray-200 bg-transparent p-0 shadow-none ring-offset-2 transition hover:border-[#93C5FD] focus:outline-none focus:ring-2 focus:ring-[#93C5FD] dark:border-[#333333] cursor-pointer"
                          onclick='viewAdvisorAvatarModal(<?= json_encode($advisorAvatarUrl, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>, <?= json_encode($advisorDisplayName, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>, <?= (int) ($advisor['id'] ?? 0) ?>, <?= json_encode($advisorAvatarLetter, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>)'
                          aria-label="ดูรูปโปรไฟล์อาจารย์"
                          title="คลิกเพื่อดูรูปใหญ่"
                        >
                          <?php if ($advisorAvatarUrl !== ''): ?>
                            <img src="<?= htmlspecialchars($advisorAvatarUrl, ENT_QUOTES, 'UTF-8') ?>" alt="<?= htmlspecialchars($advisorDisplayName, ENT_QUOTES, 'UTF-8') ?>" class="h-full w-full object-cover" />
                          <?php else: ?>
                            <div class="grid h-full w-full place-items-center bg-gray-400 font-semibold text-white text-sm">
                              <?= htmlspecialchars($advisorAvatarLetter, ENT_QUOTES, 'UTF-8') ?>
                            </div>
                          <?php endif; ?>
                          <div class="pointer-events-none absolute inset-0 flex items-center justify-center rounded-full bg-black/40 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
                            <svg class="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607zM10.5 7.5v6m3-3h-6"/></svg>
                          </div>
                        </button>
                      </td>
                      <td class="px-4 py-3 vertical-align-middle text-sm font-medium text-[#1F2937] dark:text-gray-100">
                        <?= htmlspecialchars($advisorDisplayName !== '' ? $advisorDisplayName : '-', ENT_QUOTES, 'UTF-8') ?>
                      </td>
                      <td class="w-[210px] px-4 py-3 vertical-align-middle text-center whitespace-nowrap">
                        <div class="flex items-center justify-center gap-2 whitespace-nowrap">
                          <!-- Edit Avatar Button -->
                          <button
                            type="button"
                            class="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-gray-200 bg-white text-gray-600 transition hover:border-[#93C5FD] hover:bg-blue-50 hover:text-blue-600 dark:border-[#333333] dark:bg-[#1e1e1e] dark:text-gray-300 dark:hover:border-blue-500/50 dark:hover:bg-blue-950/40 dark:hover:text-blue-400"
                            onclick='openAdvisorAvatarModal(<?= (int) ($advisor['id'] ?? 0) ?>, <?= json_encode($advisorAvatarFile, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>, <?= json_encode($advisorAvatarLetter, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>)'
                            title="เปลี่ยนรูปโปรไฟล์อาจารย์"
                            aria-label="เปลี่ยนรูปโปรไฟล์อาจารย์"
                          >
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8">
                              <path stroke-linecap="round" stroke-linejoin="round" d="M6.827 6.175A2.31 2.31 0 015.186 7.23c-.38.054-.757.112-1.134.175C2.999 7.58 2.25 8.507 2.25 9.574V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9.574c0-1.067-.75-1.994-1.802-2.169a47.865 47.865 0 00-1.134-.175 2.31 2.31 0 01-1.64-1.055l-.822-1.316a2.192 2.192 0 00-1.736-1.039 48.774 48.774 0 00-5.232 0c-.693.047-1.336.425-1.736 1.039l-.821 1.316z" />
                              <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 12.75a4.5 4.5 0 11-9 0 4.5 4.5 0 019 0zM18.75 10.5h.008v.008h-.008V10.5z" />
                            </svg>
                          </button>

                          <!-- Toggle Status Button -->
                          <form method="post" action="./settings.php" class="inline-block shrink-0">
                            <input type="hidden" name="action" value="toggle_advisor_status" />
                            <?= csrf_input() ?>
                            <input type="hidden" name="advisor_id" value="<?= (int) ($advisor['id'] ?? 0) ?>" />
                            <input type="hidden" name="next_status" value="<?= $isActive ? '0' : '1' ?>" />
                            <button
                              type="submit"
                              class="inline-flex h-8 whitespace-nowrap items-center gap-1.5 rounded-lg border px-3 text-xs font-semibold transition shrink-0 <?= $isActive ? 'border-emerald-200 bg-emerald-50 text-emerald-700 hover:bg-emerald-100 dark:border-emerald-800/80 dark:bg-emerald-950/40 dark:text-emerald-400 dark:hover:bg-emerald-900/60' : 'border-gray-200 bg-gray-50 text-gray-500 hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800/50 dark:text-gray-400 dark:hover:bg-gray-800' ?>"
                              title="<?= $isActive ? 'Click to deactivate' : 'Click to activate' ?>"
                            >
                              <span class="h-1.5 w-1.5 rounded-full shrink-0 <?= $isActive ? 'bg-emerald-500' : 'bg-gray-400' ?>"></span>
                              <span><?= $isActive ? 'Active' : 'Inactive' ?></span>
                            </button>
                          </form>

                          <!-- Delete Button -->
                          <button
                            type="button"
                            class="open-delete-item-btn inline-flex h-8 w-8 items-center justify-center rounded-lg border border-[#F2C7C7] bg-[#FFF8F8] text-[#C62828] transition hover:bg-[#FFEFEF] dark:border-rose-900/60 dark:bg-rose-950/30 dark:text-rose-400 dark:hover:bg-rose-900/50"
                            data-delete-action="delete_advisor"
                            data-delete-id="<?= (int) ($advisor['id'] ?? 0) ?>"
                            data-delete-id-field="advisor_id"
                            data-delete-name="<?= htmlspecialchars($advisorDisplayName !== '' ? $advisorDisplayName : '-', ENT_QUOTES, 'UTF-8') ?>"
                            data-delete-title="ลบอาจารย์ที่ปรึกษา"
                            data-delete-message="ยืนยันการลบอาจารย์ท่านนี้ รายการโครงงานที่อ้างอิงจะถูกตั้งค่า advisor เป็นค่าว่าง"
                            title="ลบอาจารย์ท่านนี้"
                          >
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8">
                              <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                            </svg>
                          </button>
                        </div>
                      </td>
                    </tr>
                  <?php endforeach; ?>
                <?php endif; ?>
              </tbody>
            </table>
          </div>

          <form method="POST" action="./settings.php" enctype="multipart/form-data" class="mt-4 grid grid-cols-1 sm:grid-cols-12 gap-3 p-4 items-end">
            <?= csrf_input() ?>
            <input type="hidden" name="action" value="add_advisor" />
            
            <div class="sm:col-span-2">
              <input type="text" name="advisor_prefix" placeholder="คำนำหน้า" required class="h-10 w-full rounded-xl border border-[var(--border)] bg-[#F8F9FA] px-3 text-sm focus:border-[var(--mt-red)] focus:outline-none focus:ring-0 dark:bg-[#1e1e1e] dark:border-gray-700 dark:text-white dark:placeholder-gray-500 dark:focus:border-[var(--mt-red)] dark:focus:ring-[var(--mt-red)]/20" />
            </div>
            
            <div class="sm:col-span-5">
              <input type="text" name="advisor_full_name" placeholder="ชื่อ-นามสกุล" required class="h-10 w-full rounded-xl border border-[var(--border)] bg-[#F8F9FA] px-3 text-sm focus:border-[var(--mt-red)] focus:outline-none focus:ring-0 dark:bg-[#1e1e1e] dark:border-gray-700 dark:text-white dark:placeholder-gray-500 dark:focus:border-[var(--mt-red)] dark:focus:ring-[var(--mt-red)]/20" />
            </div>

            <div class="sm:col-span-3">
              <label for="advisor_avatar_upload" id="advisor_avatar_label" class="flex h-10 w-full cursor-pointer items-center justify-center gap-2 rounded-xl border border-[#DFE2E6] bg-white px-3 text-sm text-[#6B7280] transition-colors hover:bg-gray-50 overflow-hidden dark:bg-[#1e1e1e] dark:border-[#333333] dark:text-gray-300 dark:hover:bg-gray-800">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 shrink-0 text-[#9CA3AF]" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clip-rule="evenodd" /></svg>
                <span id="advisor_avatar_text" class="truncate">อัปโหลดรูปภาพ</span>
              </label>
              <input type="file" id="advisor_avatar_upload" name="advisor_avatar" accept="image/jpeg,image/png,image/webp,image/gif" class="hidden" onchange="document.getElementById('advisor_avatar_text').textContent = this.files[0] ? this.files[0].name : 'อัปโหลดรูปภาพ';" />
            </div>

            <div class="sm:col-span-2">
              <button type="submit" class="h-10 w-full rounded-xl bg-[var(--mt-red)] px-5 text-sm font-semibold text-white hover:bg-[var(--mt-red-dark)]">เพิ่ม</button>
            </div>
          </form>
        </section>
        </div>
      </main>
    </div>
      </div>

  <div id="delete-item-modal" class="modal-overlay" aria-hidden="true">
    <div class="modal-panel w-full max-w-[430px] overflow-hidden rounded-2xl border-t-4 border-[var(--mt-red)] bg-white shadow-[0_24px_60px_rgba(0,0,0,0.35)] dark:bg-[#1e1e1e] dark:border-[#333333]">
      <div class="flex items-start justify-between border-b border-[#E5E7EB] px-6 py-5 dark:border-[#333333]">
        <div class="flex min-w-0 flex-1 items-start gap-3">
          <div class="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#FFEDEE] text-[var(--mt-red)] dark:bg-rose-950/40 dark:text-rose-400">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path stroke-linecap="round" stroke-linejoin="round" d="M3 6.75h18M9.75 6.75V5.25A2.25 2.25 0 0112 3h0a2.25 2.25 0 012.25 2.25v1.5m-7.5 0L7.5 19.5A2.25 2.25 0 009.75 21h4.5a2.25 2.25 0 002.25-1.5l.75-12.75M10 11.25v5.5m4-5.5v5.5"/></svg>
          </div>
          <div class="min-w-0">
            <h3 id="delete-item-title" class="font-display text-[24px] leading-none text-[#17191C] dark:text-white">ยืนยันการลบรายการ</h3>
            <p id="delete-item-message" class="mt-1.5 text-sm leading-snug text-[#6B7280] dark:text-gray-300">การลบข้อมูลนี้ไม่สามารถย้อนกลับได้</p>
          </div>
        </div>
        <button type="button" id="close-delete-item-modal" class="text-3xl leading-none text-[#9AA0A6] hover:text-[#5F6368] dark:text-gray-400 dark:hover:text-gray-200">&times;</button>
      </div>
      <div class="px-6 py-5">
        <div class="mb-2 block text-[12px] font-bold uppercase tracking-[0.08em] text-[#9AA0A6]">รายการที่เลือก</div>
        <div id="delete-item-name" class="truncate rounded-xl border border-[#E5E7EB] bg-[#F8F9FA] px-4 py-3 text-sm font-semibold text-[#1E1E1E] dark:border-[#333333] dark:bg-[#262626] dark:text-gray-100"></div>
        <div class="mt-6 grid grid-cols-2 gap-3">
          <button type="button" id="cancel-delete-item-modal" class="h-12 rounded-xl border border-[#E0E0E0] bg-white text-[16px] font-semibold text-[#555] hover:bg-[#F8F9FA] dark:border-[#333333] dark:bg-[#1e1e1e] dark:text-gray-300 dark:hover:bg-gray-800">ยกเลิก</button>
          <button type="button" id="confirm-delete-item-btn" class="inline-flex h-12 items-center justify-center gap-2 rounded-xl border-0 bg-[var(--mt-red)] text-[16px] font-semibold text-white hover:bg-[var(--mt-red-dark)]">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path stroke-linecap="round" stroke-linejoin="round" d="M3 6.75h18M9.75 6.75V5.25A2.25 2.25 0 0112 3h0a2.25 2.25 0 012.25 2.25v1.5m-7.5 0L7.5 19.5A2.25 2.25 0 009.75 21h4.5a2.25 2.25 0 002.25-1.5l.75-12.75M10 11.25v5.5m4-5.5v5.5"/></svg>
            ยืนยันการลบ
          </button>
        </div>
      </div>
    </div>
  </div>

  <form id="delete-item-form" method="post" action="./settings.php" hidden>
    <input type="hidden" name="action" id="delete-item-action-input" value="" />
    <?= csrf_input() ?>
    <input type="hidden" name="year_id" id="delete-year-id-input" value="" />
    <input type="hidden" name="category_id" id="delete-category-id-input" value="" />
    <input type="hidden" name="advisor_id" id="delete-advisor-id-input" value="" />
  </form>

  <!-- Modal Wrapper (ฉากหลัง) -->
  <div id="advisorAvatarModal" class="fixed inset-0 z-[100] hidden items-center justify-center bg-black/60 backdrop-blur-sm transition-opacity p-4" role="dialog" aria-modal="true" aria-labelledby="advisorAvatarModalTitle">
    <div class="relative z-[101] w-full max-w-md transform rounded-2xl bg-white p-6 shadow-2xl transition-all dark:bg-[#1e1e1e] dark:border dark:border-[#333333]">
      <!-- Header -->
      <div class="mb-4 flex items-center justify-between">
        <h3 id="advisorAvatarModalTitle" class="text-lg font-bold text-gray-900 dark:text-white">เปลี่ยนรูปโปรไฟล์</h3>
        <button type="button" onclick="closeAdvisorAvatarModal()" class="text-gray-400 transition-colors hover:text-gray-600 dark:text-gray-400 dark:hover:text-gray-200" aria-label="ปิด">
          <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
        </button>
      </div>

      <!-- Form -->
      <form id="advisor-avatar-form" action="./settings.php" method="POST" enctype="multipart/form-data" class="flex flex-col items-center w-full">
        <?= csrf_input() ?>
        <input type="hidden" name="update_advisor_avatar" value="1" />
        <input type="hidden" name="advisor_id" id="modal_advisor_id" value="" />

        <!-- Avatar Preview -->
        <div id="advisor-preview-container" class="relative mb-4 flex h-24 w-24 items-center justify-center overflow-hidden rounded-full border-2 border-gray-100 bg-gray-50 shadow-sm dark:border-[#333333] dark:bg-[#262626]">
          <img id="modal_avatar_preview" src="" alt="Preview" class="hidden h-full w-full object-cover" />
          <svg id="modal_avatar_initial" xmlns="http://www.w3.org/2000/svg" class="hidden h-10 w-10 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true"><path d="M10 10a4 4 0 100-8 4 4 0 000 8z"/><path fill-rule="evenodd" d="M.458 16.042C1.732 13.133 4.522 11 10 11s8.268 2.133 9.542 5.042A1 1 0 0118.63 17H1.37a1 1 0 01-.912-1.458z" clip-rule="evenodd"/></svg>
        </div>
        <div id="advisor-cropper-container" class="hidden mb-4 w-full h-[280px] overflow-hidden bg-[#F3F4F6] border border-[#E5E7EB] rounded-xl dark:bg-[#262626] dark:border-[#333333]">
          <img id="advisor-cropper-image" src="" alt="Crop" class="max-w-full block">
        </div>

        <!-- Upload Trigger Button -->
        <label class="mb-2 cursor-pointer rounded-full bg-[var(--mt-red,#D32F2F)] px-5 py-2 text-sm font-medium text-white shadow-sm transition-colors hover:bg-red-700">
          เลือกรูปภาพใหม่
          <input type="file" name="advisor_avatar" id="advisor_avatar_input" class="hidden" accept="image/jpeg, image/png, image/webp, image/gif" required onchange="previewAdvisorAvatar(event)" />
        </label>

        <p class="mb-6 text-[11px] text-gray-500 dark:text-gray-400">รองรับ JPG, PNG, WEBP (ขนาดไม่เกิน 2MB)</p>

        <!-- Footer Buttons -->
        <div class="flex w-full justify-center gap-3 border-t border-gray-100 pt-4">
          <button type="button" onclick="closeAdvisorAvatarModal()" class="rounded-lg border border-gray-300 bg-white px-5 py-2 text-sm font-medium text-gray-600 transition-colors hover:bg-gray-50 dark:border-[#333333] dark:bg-[#1e1e1e] dark:text-gray-300 dark:hover:bg-gray-800">ยกเลิก</button>
          <button type="submit" class="rounded-lg bg-[var(--mt-red,#D32F2F)] px-5 py-2 text-sm font-medium text-white shadow-sm shadow-red-500/30 transition-colors hover:bg-red-700">บันทึกรูปภาพ</button>
        </div>
      </form>
    </div>
  </div>

  <!-- View Advisor Photo Modal -->
  <div id="viewAdvisorPhotoModal" class="fixed inset-0 z-[100] hidden items-center justify-center bg-black/70 backdrop-blur-sm transition-opacity p-4" role="dialog" aria-modal="true">
    <div class="relative z-[101] w-full max-w-sm transform rounded-2xl bg-white p-6 shadow-2xl transition-all dark:bg-[#1e1e1e] dark:border dark:border-[#333333] text-center">
      <button type="button" onclick="closeViewAdvisorPhotoModal()" class="absolute right-4 top-4 text-gray-400 hover:text-gray-600 dark:text-gray-400 dark:hover:text-gray-200" aria-label="ปิด">
        <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
      </button>
      <h3 id="view_photo_name" class="text-base font-bold text-gray-900 dark:text-white mb-4">อาจารย์ที่ปรึกษา</h3>
      <div class="relative mx-auto mb-5 flex h-48 w-48 items-center justify-center overflow-hidden rounded-full border-4 border-gray-100 shadow-md dark:border-[#333333] bg-gray-100 dark:bg-[#262626]">
        <img id="view_photo_img" src="" alt="Advisor Photo" class="h-full w-full object-cover hidden" />
        <div id="view_photo_fallback" class="hidden text-5xl font-bold text-gray-400">A</div>
      </div>
      <div class="flex items-center justify-center gap-3">
        <button type="button" onclick="closeViewAdvisorPhotoModal()" class="rounded-xl border border-gray-200 bg-white px-4 py-2 text-xs font-semibold text-gray-600 hover:bg-gray-50 dark:border-[#333333] dark:bg-[#1e1e1e] dark:text-gray-300 dark:hover:bg-gray-800">ปิด</button>
        <button type="button" id="view_photo_edit_btn" class="inline-flex items-center gap-1.5 rounded-xl bg-[var(--mt-red,#D32F2F)] px-4 py-2 text-xs font-semibold text-white hover:bg-red-700 shadow-sm">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125"/></svg>
          <span>เปลี่ยนรูปภาพ</span>
        </button>
      </div>
    </div>
  </div>

  <script>
    let advisorCropper = null;

    function viewAdvisorAvatarModal(url, name, id, letter) {
      const modal = document.getElementById('viewAdvisorPhotoModal');
      const imgEl = document.getElementById('view_photo_img');
      const nameEl = document.getElementById('view_photo_name');
      const fallbackEl = document.getElementById('view_photo_fallback');
      const editBtn = document.getElementById('view_photo_edit_btn');

      if (nameEl) nameEl.textContent = name || 'อาจารย์ที่ปรึกษา';

      if (url) {
        if (imgEl) {
          imgEl.src = url;
          imgEl.classList.remove('hidden');
        }
        if (fallbackEl) fallbackEl.classList.add('hidden');
      } else {
        if (imgEl) imgEl.classList.add('hidden');
        if (fallbackEl) {
          fallbackEl.textContent = letter || 'A';
          fallbackEl.classList.remove('hidden');
        }
      }

      if (editBtn) {
        editBtn.onclick = function () {
          closeViewAdvisorPhotoModal();
          openAdvisorAvatarModal(id, url ? url.split('/').pop() : '', letter);
        };
      }

      if (modal) {
        modal.classList.remove('hidden');
        modal.classList.add('flex');
      }
    }

    function closeViewAdvisorPhotoModal() {
      const modal = document.getElementById('viewAdvisorPhotoModal');
      if (modal) {
        modal.classList.add('hidden');
        modal.classList.remove('flex');
      }
    }

    function openAdvisorAvatarModal(id, avatarFilename, initial) {
      document.getElementById('modal_advisor_id').value = id;

      const previewImg = document.getElementById('modal_avatar_preview');
      const initialSpan = document.getElementById('modal_avatar_initial');
      const fileInput = document.getElementById('advisor_avatar_input');
      const previewContainer = document.getElementById('advisor-preview-container');
      const cropperContainer = document.getElementById('advisor-cropper-container');

      if (fileInput) fileInput.value = '';
      if (previewContainer) previewContainer.classList.remove('hidden');
      if (cropperContainer) cropperContainer.classList.add('hidden');

      if (advisorCropper) {
        advisorCropper.destroy();
        advisorCropper = null;
      }

      if (avatarFilename) {
        previewImg.src = '../uploads/advisors/' + encodeURIComponent(avatarFilename);
        previewImg.classList.remove('hidden');
        initialSpan.classList.add('hidden');
      } else {
        previewImg.classList.add('hidden');
        previewImg.src = '';
        initialSpan.classList.remove('hidden');
      }

      const modal = document.getElementById('advisorAvatarModal');
      modal.classList.remove('hidden');
      modal.classList.add('flex');
    }

    function closeAdvisorAvatarModal() {
      const modal = document.getElementById('advisorAvatarModal');
      modal.classList.add('hidden');
      modal.classList.remove('flex');
      if (advisorCropper) {
        advisorCropper.destroy();
        advisorCropper = null;
      }
    }

    function previewAdvisorAvatar(event) {
      const input = event.target;
      if (!input.files || !input.files[0]) return;
      const maxBytes = 2 * 1024 * 1024;
      if (input.files[0].size > maxBytes) {
        window.alert('ไฟล์ต้องไม่เกิน 2MB');
        input.value = '';
        return;
      }
      const reader = new FileReader();
      reader.onload = function (e) {
        const previewContainer = document.getElementById('advisor-preview-container');
        const cropperContainer = document.getElementById('advisor-cropper-container');
        const cropperImage = document.getElementById('advisor-cropper-image');

        if (previewContainer) previewContainer.classList.add('hidden');
        if (cropperContainer) cropperContainer.classList.remove('hidden');

        cropperImage.src = e.target.result;

        if (advisorCropper) {
            advisorCropper.destroy();
        }
        advisorCropper = new Cropper(cropperImage, {
            aspectRatio: 1,
            viewMode: 1,
            autoCropArea: 1,
        });
      };
      reader.readAsDataURL(input.files[0]);
    }

    document.addEventListener('DOMContentLoaded', function() {
        const advForm = document.getElementById('advisor-avatar-form');
        if (advForm) {
            advForm.addEventListener('submit', function(e) {
                e.preventDefault();
                const submitBtn = advForm.querySelector('button[type="submit"]');

                if (advisorCropper) {
                    submitBtn.disabled = true;
                    submitBtn.innerHTML = 'กำลังบันทึก...';

                    advisorCropper.getCroppedCanvas({ width: 400, height: 400 }).toBlob(function(blob) {
                        const formData = new FormData(advForm);
                        formData.set('advisor_avatar', blob, 'advisor_cropped.jpg');

                        fetch(advForm.action, {
                            method: 'POST',
                            body: formData
                        })
                        .then(function(response) {
                            if (response.ok) {
                                window.location.reload();
                            } else {
                                alert('เกิดข้อผิดพลาดในการอัปโหลด');
                                submitBtn.disabled = false;
                                submitBtn.innerHTML = 'บันทึกรูปภาพ';
                            }
                        })
                        .catch(function() {
                            alert('เกิดข้อผิดพลาดในการเชื่อมต่อ');
                            submitBtn.disabled = false;
                            submitBtn.innerHTML = 'บันทึกรูปภาพ';
                        });
                    }, 'image/jpeg', 0.9);
                } else {
                    closeAdvisorAvatarModal();
                }
            });
        }
    });

    (function () {
      const registrationToggle = document.getElementById('registration-open');
      const registrationForm = document.getElementById('registration-form');
      const registrationTrack = document.getElementById('registration-track');
      const registrationThumb = document.getElementById('registration-thumb');

      function syncRegistrationSwitch() {
        if (!registrationToggle || !registrationTrack || !registrationThumb) return;
        if (registrationToggle.checked) {
          registrationTrack.classList.remove('border-[#D0D5DD]', 'bg-white');
          registrationTrack.classList.add('border-[#10B981]', 'bg-[#ECFDF5]');
          registrationThumb.classList.remove('left-1', 'bg-[#9CA3AF]');
          registrationThumb.classList.add('left-7', 'bg-[#10B981]');
        } else {
          registrationTrack.classList.remove('border-[#10B981]', 'bg-[#ECFDF5]');
          registrationTrack.classList.add('border-[#D0D5DD]', 'bg-white');
          registrationThumb.classList.remove('left-7', 'bg-[#10B981]');
          registrationThumb.classList.add('left-1', 'bg-[#9CA3AF]');
        }
      }

      syncRegistrationSwitch();
      if (registrationToggle && registrationForm) {
        registrationToggle.addEventListener('change', function () {
          syncRegistrationSwitch();
          registrationForm.submit();
        });
      }

      const deleteModal = document.getElementById('delete-item-modal');
      const deleteForm = document.getElementById('delete-item-form');
      const deleteActionInput = document.getElementById('delete-item-action-input');
      const deleteYearIdInput = document.getElementById('delete-year-id-input');
      const deleteCategoryIdInput = document.getElementById('delete-category-id-input');
      const deleteAdvisorIdInput = document.getElementById('delete-advisor-id-input');
      const deleteNameElement = document.getElementById('delete-item-name');
      const deleteTitleElement = document.getElementById('delete-item-title');
      const deleteMessageElement = document.getElementById('delete-item-message');
      const closeDeleteModalBtn = document.getElementById('close-delete-item-modal');
      const cancelDeleteModalBtn = document.getElementById('cancel-delete-item-modal');
      const confirmDeleteModalBtn = document.getElementById('confirm-delete-item-btn');

      function resetDeleteTargets() {
        if (deleteYearIdInput) deleteYearIdInput.value = '';
        if (deleteCategoryIdInput) deleteCategoryIdInput.value = '';
        if (deleteAdvisorIdInput) deleteAdvisorIdInput.value = '';
      }

      function openDeleteModal() {
        if (!deleteModal) return;
        deleteModal.classList.add('open');
        deleteModal.setAttribute('aria-hidden', 'false');
        requestAnimationFrame(function () {
          deleteModal.classList.add('is-visible');
        });
      }

      let pendingAdvisorDeleteBtn = null;

      function resetAdvisorDeleteButton() {
        if (!(pendingAdvisorDeleteBtn instanceof HTMLButtonElement)) return;
        pendingAdvisorDeleteBtn.disabled = false;
        pendingAdvisorDeleteBtn.classList.remove('cursor-not-allowed');
        pendingAdvisorDeleteBtn.innerHTML = pendingAdvisorDeleteBtn.dataset.originalHtml || pendingAdvisorDeleteBtn.innerHTML;
        pendingAdvisorDeleteBtn = null;
      }

      function closeDeleteModal() {
        if (!deleteModal) return;
        deleteModal.classList.remove('is-visible');
        window.setTimeout(function () {
          deleteModal.classList.remove('open');
          deleteModal.setAttribute('aria-hidden', 'true');
        }, 300);
        resetAdvisorDeleteButton();
      }

      function bindDeleteModalFromButton(button) {
        if (!button || !deleteActionInput) return;
        resetDeleteTargets();

        const action = button.getAttribute('data-delete-action') || '';
        const idValue = button.getAttribute('data-delete-id') || '';
        const idField = button.getAttribute('data-delete-id-field') || '';
        const itemName = button.getAttribute('data-delete-name') || '-';
        const itemTitle = button.getAttribute('data-delete-title') || 'ยืนยันการลบรายการ';
        const itemMessage = button.getAttribute('data-delete-message') || 'การลบข้อมูลนี้ไม่สามารถย้อนกลับได้';

        deleteActionInput.value = action;
        if (idField === 'year_id' && deleteYearIdInput) deleteYearIdInput.value = idValue;
        if (idField === 'category_id' && deleteCategoryIdInput) deleteCategoryIdInput.value = idValue;
        if (idField === 'advisor_id' && deleteAdvisorIdInput) deleteAdvisorIdInput.value = idValue;
        if (deleteNameElement) deleteNameElement.textContent = itemName;
        if (deleteTitleElement) deleteTitleElement.textContent = itemTitle;
        if (deleteMessageElement) deleteMessageElement.textContent = itemMessage;
      }

      document.addEventListener('click', function (e) {
        const openBtn = e.target.closest('.open-delete-item-btn');
        if (!openBtn) return;
        e.preventDefault();
        resetAdvisorDeleteButton();
        if ((openBtn.getAttribute('data-delete-action') || '') === 'delete_advisor') {
          pendingAdvisorDeleteBtn = openBtn;
        } else {
          pendingAdvisorDeleteBtn = null;
        }
        bindDeleteModalFromButton(openBtn);
        openDeleteModal();
      });

      if (closeDeleteModalBtn) closeDeleteModalBtn.addEventListener('click', closeDeleteModal);
      if (cancelDeleteModalBtn) cancelDeleteModalBtn.addEventListener('click', closeDeleteModal);
      if (confirmDeleteModalBtn && deleteForm) {
        confirmDeleteModalBtn.addEventListener('click', function () {
          const action = deleteActionInput ? deleteActionInput.value : '';
          if (action === 'delete_advisor' && pendingAdvisorDeleteBtn instanceof HTMLButtonElement) {
            const button = pendingAdvisorDeleteBtn;
            if (!button.dataset.originalHtml) {
              button.dataset.originalHtml = button.innerHTML;
            }
            button.disabled = true;
            button.classList.add('cursor-not-allowed');
            button.innerHTML = `
              <svg class="animate-spin h-4 w-4 text-red-600 inline-block" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
            `;
          }
          deleteForm.submit();
        });
      }
      if (deleteModal) {
        deleteModal.addEventListener('click', function (e) {
          if (e.target === deleteModal) closeDeleteModal();
        });
      }
      document.addEventListener('keydown', function (e) {
        if (e.key === 'Escape') {
          closeDeleteModal();
          if (typeof closeAdvisorAvatarModal === 'function') {
            closeAdvisorAvatarModal();
          }
        }
      });

      var advisorAvatarModal = document.getElementById('advisorAvatarModal');
      if (advisorAvatarModal) {
        advisorAvatarModal.addEventListener('click', function (e) {
          if (e.target === advisorAvatarModal) {
            closeAdvisorAvatarModal();
          }
        });
      }
    })();

    // --- ระบบจำตำแหน่งหน้าจอ (Scroll Persistence สำหรับ Dashboard Layout) ---
    (function () {
      // ค้นหากรอบที่ใช้เลื่อนขึ้นลงจริงๆ
      const scrollContainer = document.querySelector('main.overflow-y-auto');
      if (!scrollContainer) return;

      // 1. บันทึกตำแหน่งทุกครั้งที่มีการเลื่อนหน้าจอ
      scrollContainer.addEventListener('scroll', function () {
        sessionStorage.setItem('settings_main_scroll', String(scrollContainer.scrollTop));
      }, { passive: true });

      // 2. ดักจับการกด Submit ฟอร์มเพื่อจดจำตำแหน่งล่าสุดก่อนโหลดหน้าใหม่
      document.querySelectorAll('form').forEach(function(form) {
        form.addEventListener('submit', function() {
          sessionStorage.setItem('settings_main_scroll', String(scrollContainer.scrollTop));
        });
      });

      // 3. คืนค่าตำแหน่งเมื่อหน้าเว็บโหลดเสร็จ
      document.addEventListener('DOMContentLoaded', function () {
        const scrollPos = sessionStorage.getItem('settings_main_scroll');
        if (scrollPos) {
          // คืนค่าตำแหน่งทันที
          scrollContainer.scrollTop = parseInt(scrollPos, 10);
          
          // และย้ำอีกครั้งเพื่อให้แน่ใจว่ารูปภาพหรือตารางโหลดพื้นที่เสร็จแล้ว
          setTimeout(function() {
            scrollContainer.scrollTop = parseInt(scrollPos, 10);
          }, 50);
        }
      });
    })();
  </script>
  <?php require_once __DIR__ . '/../config/site_lang_script.php'; ?>
</body>
</html>

