-- ============================================================
--  rmutimt_gallery — PostgreSQL / Supabase schema
--  Converted from MySQL dump (rmutimt_gallery.sql)
--
--  วิธีใช้:
--   1. เปิด Supabase -> SQL Editor -> New query
--   2. วางไฟล์นี้ทั้งหมด -> Run
--  (หรือ:  psql "$DATABASE_URL" -f database_supabase.sql )
-- ============================================================

-- ------------------------------------------------------------
--  Helper: ให้โค้ดเดิมเรียก FIND_IN_SET(needle, csv) ได้เหมือน MySQL
--  คืนค่าตำแหน่ง (>=1) ถ้าเจอ, 0 ถ้าไม่เจอ  -> ใช้เป็นเงื่อนไข truthy ได้
-- ------------------------------------------------------------
-- ------------------------------------------------------------
--  Helper: shim ให้โค้ดที่เขียนแบบ MySQL ยังใช้ได้
--  DATABASE()  -> ชื่อ schema ปัจจุบัน (ปกติ 'public')
--  ใช้ในเควรี information_schema เช่น  WHERE table_schema = DATABASE()
-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS database();
DROP FUNCTION IF EXISTS find_in_set(text, text);

CREATE OR REPLACE FUNCTION database()
RETURNS text
LANGUAGE sql
STABLE
AS $$
    SELECT current_schema()::text;
$$;

CREATE OR REPLACE FUNCTION find_in_set(needle text, haystack text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT needle = ANY(
        string_to_array(regexp_replace(COALESCE(haystack, ''), '\s', '', 'g'), ',')
    );
$$;

-- ------------------------------------------------------------
--  Tables
-- ------------------------------------------------------------
DROP TABLE IF EXISTS project_files CASCADE;
DROP TABLE IF EXISTS project_members CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS advisors CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS academic_years CASCADE;

CREATE TABLE academic_years (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year varchar(20) NOT NULL
);
CREATE UNIQUE INDEX uniq_academic_years_year ON academic_years (year);

CREATE TABLE advisors (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefix          varchar(30)  NOT NULL,
    full_name       varchar(190) NOT NULL,
    avatar_filename varchar(255),
    is_active       smallint     NOT NULL DEFAULT 1,
    created_at      timestamp    NOT NULL DEFAULT now()
);
CREATE INDEX idx_advisors_active ON advisors (is_active);

CREATE TABLE categories (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL
);
CREATE UNIQUE INDEX uniq_categories_name ON categories (name);

CREATE TABLE users (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(150) NOT NULL,
    student_id      varchar(30),
    email           varchar(190) NOT NULL,
    avatar_filename varchar(255),
    password        varchar(255) NOT NULL,
    role            varchar(20)  NOT NULL DEFAULT 'student'
                    CHECK (role IN ('student', 'admin'))
);
CREATE UNIQUE INDEX uniq_users_email      ON users (email);
CREATE UNIQUE INDEX uniq_users_student_id ON users (student_id);
CREATE INDEX        idx_users_role        ON users (role);

CREATE TABLE projects (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_th               varchar(255) NOT NULL,
    title_en               varchar(255),
    creators               text         NOT NULL,
    advisor_id             bigint,
    category_id            bigint       NOT NULL,
    secondary_category_ids varchar(255),
    academic_year_id       bigint       NOT NULL,
    introduction           text,
    file_urls              text,
    status                 varchar(20)  NOT NULL DEFAULT 'pending'
                           CHECK (status IN ('pending', 'approved', 'rejected')),
    uploader_id            bigint       NOT NULL,
    created_at             timestamp    NOT NULL DEFAULT now(),
    drive_folder_id        varchar(255),
    CONSTRAINT fk_projects_academic_year FOREIGN KEY (academic_year_id)
        REFERENCES academic_years (id) ON UPDATE CASCADE,
    CONSTRAINT fk_projects_advisor FOREIGN KEY (advisor_id)
        REFERENCES advisors (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_projects_category FOREIGN KEY (category_id)
        REFERENCES categories (id) ON UPDATE CASCADE,
    CONSTRAINT fk_projects_uploader FOREIGN KEY (uploader_id)
        REFERENCES users (id) ON UPDATE CASCADE
);
CREATE INDEX idx_projects_status           ON projects (status);
CREATE INDEX idx_projects_category_id      ON projects (category_id);
CREATE INDEX idx_projects_academic_year_id ON projects (academic_year_id);
CREATE INDEX idx_projects_advisor_id       ON projects (advisor_id);
CREATE INDEX idx_projects_uploader_id      ON projects (uploader_id);

CREATE TABLE project_members (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      bigint       NOT NULL,
    student_id      varchar(50)  DEFAULT '',
    full_name       varchar(255) NOT NULL,
    avatar_filename varchar(255)
);
CREATE INDEX idx_project_members_project_id ON project_members (project_id);

CREATE TABLE system_settings (
    key_name   varchar(100) PRIMARY KEY,
    value_text varchar(255) NOT NULL
);

-- ตารางเสริม (โค้ดเรียกแบบมี guard tableExists; สร้างไว้ให้ครบ)
CREATE TABLE project_files (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    bigint       NOT NULL,
    file_type     varchar(50)  NOT NULL,
    file_id       varchar(255),
    file_name     varchar(255),
    web_view_link text
);
CREATE INDEX idx_project_files_project_id ON project_files (project_id);
